services:
  ubuntu:
    image: 'ubuntu:latest'
    volumes:
      - ./logs/:/logs/
      - ./scripts/0.sh:/tmp/0.sh
      - ./scripts/1.sh:/tmp/1.sh
      - ./scripts/2.sh:/tmp/2.sh
      - ./scripts/3.sh:/tmp/3.sh
      - ./scripts/4.sh:/tmp/4.sh
      - ./scripts/5.sh:/tmp/5.sh
    command: 'sh -c "while true; do sleep 5000; done;"'
